# SPRING PROPERTIES
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gro?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: mehrdad
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        format_sql: true
        ddl-auto: none
    show-sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  profiles:
    include:
      'query'

# JWT : JSON WEB TOKEN PROPERTIES
jwt:
  header: Authorization
  secret: password
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

quartz:
  configLocation: quartz.properties
exception:
  notification-not-found: Notification not found
  rpi-component-not-found: Component with supplied id was not found
  invalid-rpi-component-type: Invalid Rpi component type
  pin-not-found: Pin not found
  invalid-relay-state: Invalid Relay state

mqtt:
  url: tcp://localhost:8161
  username: admin
  password: admin
  topics:
    relay:
      change: change
      poll: poll

sse:
  event:
    humidity: humidity
    temperature: temperature
    proximity: proximidity
    relay: relay
    moisture: moisture
    notification: notification

twilio:
  account:
    sid: TWILIO SID
    auth_token: TWILIO AUTH TOKEN
  phone:
    inbound: TWILIO INBOUND PHONE NUMBER
    outbound: TWILIO OUTBOUND PHONE NUMBER

    
     